<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
 
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?php $_e('Sonder'); ?></title>
    
    <!-- Bootstrap core CSS -->
    <link href="/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/css/admin.css" rel="stylesheet" type="text/css">

    <?php echo $this->template('_base_scripts.phtml'); ?>

    <script src="/node_modules/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>

</head>
<body>

<div id="barba-wrapper">
  <div class="barba-container">
    <?php echo $this->template('admin/_header.phtml'); ?>

    <div class="container-fluid">
      <div class="row">

        <?php echo $this->template('admin/_sidebar.phtml'); ?>

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <?php if (isset($_content)) echo $_content; ?>
        </div>

      </div>
    </div>

  </div>
</div>

</body>
</html>
