<div id="container">
<div id="header">
    <h1>The JSON Store</h1>
</div>
<div id="main">
</div>
</div>

<link rel="stylesheet" href="/assets/css/jsonstore.css" type="text/css" media="screen" charset="utf-8"/>

<script src="/node_modules/jquery/dist/jquery.min.js" type="text/javascript" charset="utf-8"></script>
<script src="/node_modules/sammy/lib/min/sammy-latest.min.js" type="text/javascript" charset="utf-8"></script>
<script src="/node_modules/sammy/lib/min//plugins/sammy.template-latest.min.js" type="text/javascript" charset="utf-8"></script>
<script src="/node_modules/sammy/lib/min//plugins/sammy.json-latest.min.js" type="text/javascript" charset="utf-8"></script>
<script src="/node_modules/sammy/lib/min//plugins/sammy.storage-latest.min.js" type="text/javascript" charset="utf-8"></script>
<script src="/assets/js/portal.js" type="text/javascript" charset="utf-8"></script>
